version: '3.8'
services:
  app:
    build: .
    image: maryam271291/sit323-737-2024-t1--prac7p
    ports:
      - '3041:3040'
    environment:
      - PORT=3040
    container_name: my-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3040/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - my-net

  app1:
    build: .
    image: maryam271291/sit323-737-2024-t1--prac7p
    ports:
      - '3044:3040'
    environment:
      - PORT=3040
    container_name: my-app1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3040/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - my-net

networks:
  my-net:
    driver: bridge